import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Service Search",
    description: "Generated by create next app",
};

export default function AuthLayout({children,}: Readonly<{children: React.ReactNode;}>) {
return(<>
    {children}
    
</>);
}