import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}